apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}-deployment
  namespace: {{ .Values.deploy.namespace }}
  labels:
    app: {{ .Values.deploy.name }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.deploy.imageSecret }}
      containers:
      - name: {{ .Values.deploy.name }}
        image: {{ .Values.deploy.image }}:{{ .Values.deploy.tag }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: {{ .Values.probe.livenesspath }}
            port: {{ .Values.deploy.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.probe.readinesspath }}
            port: {{ .Values.deploy.port }}
          initialDelaySeconds: 30
          successThreshold: 1
          periodSeconds: 10
        resources:
          limits:
            cpu: {{ .Values.deploy.limitCpu }}
            memory: {{ .Values.deploy.limitMemory }}
          requests:
            cpu: {{ .Values.deploy.requestCpu }}
            memory: {{ .Values.deploy.requestMemory }}
        ports:
        - containerPort: {{ int .Values.deploy.targetport }}
      restartPolicy: Always
{{- if .Values.nodeselector.enabled }}
      nodeSelector:
          module: {{.Values.deploy.name}}
{{- end }}
{{- if .Values.tolerations.enabled }}
      tolerations:
      - key: {{ .Values.tolerations.key }}
        operator: {{ .Values.tolerations.operator }}
        value: {{ .Values.tolerations.value }}
        effect: {{ .Values.tolerations.effect }}
{{- end }}
{{- if .Values.affinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinity.key }}
                operator: {{ .Values.affinity.operator }}
                values: 
                  {{- range .Values.affinity.values }}
                  - {{ . }}
                  {{- end }}
{{- end }}